branches:
  only:
    - master
  except:
    - gh-pages

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: x86_64-pc-windows-gnu
  - TARGET: i686-pc-windows-gnu
  api:
    secure: ZQiyxjBbshVpIVZbZl9h23yGuqlq+8j615c0B2z7VxdEAW1wggIfkebJqpgZclk2

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-beta-${env:TARGET}.exe"
  - rust-beta-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
  - ps: $env:PATH="$env:PATH;C:\Rust\bin"
  - rustc -V
  - cargo -V

build: false

test_script:
  - ps: $env:RUST_TEST_THREADS=1
  - ps: echo "let's save some clipboard!" | Clip
  - cargo test
