[package]
name = "clipboard-win"
version = "0.3.1"
authors = ["DoumanAsh <custparasite@gmx.se>"]
description = "Utilities to interact with clipboard."
repository = "https://github.com/DoumanAsh/clipboard-win"
documentation = "http://doumanash.github.io/clipboard-win/doc/clipboard_win/index.html"
license = "MIT"

[dependencies]
libc = "*"
winapi = "*"
user32-sys = "*"
kernel32-sys = "*"

[lib]
name = "clipboard_win"
path = "src/lib.rs"
test = false
