[package]
name = "clipboard-win"
version = "2.1.0"
authors = ["Douman <douman@gmx.se>"]
description = "Provides simple way to interact with Windows clipboard."
license = "MIT"

keywords = ["Windows", "winapi", "clipboard"]
categories = []

repository = "https://github.com/DoumanAsh/clipboard-win"
documentation = "https://docs.rs/clipboard-win/*/x86_64-pc-windows-msvc/clipboard_win/"

readme = "README.md"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[badges]
appveyor = { repository = "https://github.com/DoumanAsh/clipboard-win", branch = "master", service = "github" }

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
default-features = false
features = [
    "basetsd",
    "winbase",
    "winuser"
]

[lib]
name = "clipboard_win"
path = "src/lib.rs"
test = false
