[package]
name = "clipboard-win"
version = "1.8.0"
authors = ["Douman <douman@gmx.se>"]
description = "Library to interact with Windows clipboard."
repository = "https://github.com/DoumanAsh/clipboard-win"
documentation = "http://doumanash.github.io/clipboard-win/doc/clipboard_win/index.html"
license = "MIT"
keywords = ["Windows", "winapi", "clipboard"]

[dependencies]
winapi = "^0.2.5"
user32-sys = "^0.2.0"
kernel32-sys = "^0.2.1"
windows-error = "^1.0.0"

[lib]
name = "clipboard_win"
path = "src/lib.rs"
test = false
