[package]
name = "clipboard-win"
version = "3.1.1"
authors = ["Douman <douman@gmx.se>"]
description = "Provides simple way to interact with Windows clipboard."
license = "MIT"

keywords = ["Windows", "winapi", "clipboard"]
categories = ["os::windows-apis"]

repository = "https://github.com/DoumanAsh/clipboard-win"
documentation = "https://docs.rs/crate/clipboard-win"

readme = "README.md"
edition = "2018"

include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[dependencies]
lazy-bytes-cast = "5"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
default-features = false
features = [
    "std",
    "basetsd",
    "shellapi",
    "winbase",
    "winuser",
    "stringapiset",
]
