[package]
name = "clipboard-win"
version = "1.1.0"
authors = ["Douman <custparasite@gmx.se>"]
description = "Utilities to interact with windows clipboard."
repository = "https://github.com/DoumanAsh/clipboard-win"
documentation = "http://doumanash.github.io/clipboard-win/doc/clipboard_win/index.html"
license = "MIT"
keywords = ["Windows", "winapi", "clipboard"]

[dependencies]
libc = "*"
winapi = "*"
user32-sys = "*"
kernel32-sys = "*"

[lib]
name = "clipboard_win"
path = "src/lib.rs"
test = false
