[package]
name = "clipboard-win"
version = "2.0.0-pre.1"
authors = ["Douman <douman@gmx.se>"]
description = "Provides simple way to interact with Windows clipboard."
license = "MIT"

keywords = ["Windows", "winapi", "clipboard"]
categories = []

repository = "https://github.com/DoumanAsh/clipboard-win"
documentation = "https://docs.rs/crate/clipboard-win/"

readme = "README.md"

[badges]
appveyor = { repository = "https://github.com/DoumanAsh/clipboard-win", branch = "master", service = "github" }

[target.'cfg(windows)'.dependencies]
winapi = "^0.2.5"
user32-sys = "^0.2.0"
kernel32-sys = "^0.2.1"

[lib]
name = "clipboard_win"
path = "src/lib.rs"
test = false
